"""
Phase 7/8 – Lead Intelligence Dashboard
=========================================
Framework  : Streamlit 1.64+
Charts     : Plotly Express / Graph Objects
Data source: data/processed/cleaned_leads.csv   (loaded dynamically)
Model      : models/best_model.pkl              (Phase 5 pipeline)
Metrics    : models/ml_phase5_metrics.json
Explainability: reports/explainability_phase6.json
AI Narrative:  reports/ai_narrative.json        (Phase 8)

Views
-----
  Overview      – KPI cards + deal-stage funnel + source bar charts
  Performance   – Source-group heatmap + owner leaderboard
  Explainability– Global SHAP/permutation importance from Phase 6
  AI Insights   – Narrative executive summary + 9 structured insights (Phase 8)
  What-If Scorer– Interactive lead scoring with feature contribution bars

Run:
    streamlit run dashboard/streamlit_app.py
"""

from __future__ import annotations

import json
import os
import pickle
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# ---------------------------------------------------------------------------
# Paths  (all relative to repo root, resolved from this file's location)
# ---------------------------------------------------------------------------
ROOT            = Path(__file__).resolve().parents[1]
DATA_PATH       = ROOT / "data"  / "processed" / "cleaned_leads.csv"
MODEL_PATH      = ROOT / "models" / "best_model.pkl"
METRICS_PATH    = ROOT / "models" / "ml_phase5_metrics.json"
EXPL_PATH       = ROOT / "reports" / "explainability_phase6.json"
NARRATIVE_PATH  = ROOT / "reports" / "ai_narrative.json"

# ---------------------------------------------------------------------------
# Source-tier lookup (mirrors Phase 5 feature engineering exactly)
# ---------------------------------------------------------------------------
SOURCE_TIER: dict[str, int] = {
    "Podcast": 1, "Partner Program": 1, "Referral": 1,
    "Webinars": 1, "Content Marketing": 1,
    "LinkedIn Outreach": 2, "Cold Email": 2, "Cold Call": 2,
    "Facebook Ads": 2, "Chatbot": 2, "Retargeting Ads": 2,
    "Direct Traffic": 2, "Organic Search (SEO)": 2, "Trade Show": 2,
    "Google Ads": 2, "Social Media": 3, "Purchased List": 3,
    "Other": 3, "Website Form": 3, "Networking Event": 3,
}

# Deal-stage ordering for funnel display
STAGE_ORDER = [
    "New Lead", "Contacted", "Qualified", "Proposal Sent",
    "Negotiation", "Re-engagement", "On Hold",
    "Disqualified", "Closed Lost", "Closed Won",
]

# Colour palette
CLR_BLUE   = "#3b82d4"
CLR_GREEN  = "#22c55e"
CLR_RED    = "#ef4444"
CLR_AMBER  = "#f59e0b"
CLR_PURPLE = "#7c5cd8"
CLR_MUTED  = "#57606a"
CLR_BG     = "#f7f8fa"

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="Lead Intelligence Dashboard",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Cached loaders
# ---------------------------------------------------------------------------
@st.cache_data(show_spinner="Loading data…")
def load_data() -> pd.DataFrame:
    df = pd.read_csv(DATA_PATH)
    required = {
        "lead_owner", "company", "source", "source_group",
        "deal_stage", "notes_sentiment", "notes_word_count",
        "notes_has_text", "is_won",
    }
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"Missing required columns: {missing}")
    df["is_won"] = (
        pd.to_numeric(df["is_won"], errors="coerce").fillna(0).astype(int)
    )
    return df


@st.cache_resource(show_spinner="Loading model…")
def load_model():
    with MODEL_PATH.open("rb") as fh:
        return pickle.load(fh)


@st.cache_data(show_spinner=False)
def load_metrics() -> dict:
    if METRICS_PATH.exists():
        with METRICS_PATH.open() as fh:
            return json.load(fh)
    return {}


@st.cache_data(show_spinner=False)
def load_explainability() -> dict:
    if EXPL_PATH.exists():
        with EXPL_PATH.open() as fh:
            return json.load(fh)
    return {}


@st.cache_data(show_spinner=False)
def load_narrative() -> dict:
    """Load Phase 8 AI narrative output (pre-generated by src/ai_narrative.py)."""
    if NARRATIVE_PATH.exists():
        with NARRATIVE_PATH.open(encoding="utf-8") as fh:
            return json.load(fh)
    return {}


@st.cache_data(show_spinner=False)
def compute_freq_tables(df: pd.DataFrame) -> tuple[int, dict, dict]:
    total = len(df)
    owner_counts   = df["lead_owner"].value_counts().to_dict()
    company_counts = df["company"].value_counts().to_dict()
    return total, owner_counts, company_counts


# ---------------------------------------------------------------------------
# Feature vector builder (mirrors Phase 5 / Phase 6 exactly)
# ---------------------------------------------------------------------------
def build_vector(
    source: str, source_group: str,
    notes_sentiment: float, notes_word_count: int,
    notes_has_text: int, lead_owner: str, company: str,
    owner_counts: dict, company_counts: dict, total: int,
) -> list:
    return [
        source,
        source_group,
        float(notes_sentiment),
        int(notes_word_count),
        int(notes_has_text),
        SOURCE_TIER.get(source, 2),
        owner_counts.get(lead_owner, 0) / total,
        company_counts.get(company, 0) / total,
    ]


# ---------------------------------------------------------------------------
# Sidebar – filters & navigation
# ---------------------------------------------------------------------------
def render_sidebar(df: pd.DataFrame):
    with st.sidebar:
        st.image(
            "https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg",
            width=80,
        )
        st.markdown("## Lead Intelligence")
        st.markdown("---")

        view = st.radio(
            "View",
            ["📋 Overview", "📈 Performance", "🔬 Explainability",
             "🤖 AI Insights", "🎯 What-If Scorer"],
            index=0,
        )

        st.markdown("### Filters")
        source_options = sorted(df["source"].dropna().unique())
        selected_sources = st.multiselect(
            "Lead Source",
            source_options,
            default=source_options,
            help="Select one or more lead sources to filter the analysis.",
        )

        group_options = sorted(df["source_group"].dropna().unique())
        selected_groups = st.multiselect(
            "Source Group",
            group_options,
            default=group_options,
        )

        owner_query = st.text_input(
            "Lead Owner (search)",
            placeholder="e.g. Alice",
            help="Case-insensitive substring match on lead owner name.",
        )

        st.markdown("---")
        st.caption(
            f"Data: `{DATA_PATH.name}`  \n"
            f"Model: `{MODEL_PATH.name}`  \n"
            f"Streamlit {st.__version__}"
        )

    owner_mask = (
        df["lead_owner"].astype(str).str.contains(owner_query, case=False, na=False)
        if owner_query
        else pd.Series(True, index=df.index)
    )

    filtered = df[
        df["source"].isin(selected_sources)
        & df["source_group"].isin(selected_groups)
        & owner_mask
    ].copy()

    return view, filtered


# ---------------------------------------------------------------------------
# KPI Cards
# ---------------------------------------------------------------------------
def render_kpis(full_df: pd.DataFrame, filtered: pd.DataFrame):
    total_all   = len(full_df)
    total_filt  = len(filtered)
    rate_all    = full_df["is_won"].mean()
    rate_filt   = filtered["is_won"].mean() if total_filt else 0.0

    src_counts  = filtered["source"].value_counts()
    top_src     = src_counts.idxmax() if not src_counts.empty else "—"
    top_src_n   = int(src_counts.max()) if not src_counts.empty else 0
    top_src_rate= (
        filtered[filtered["source"] == top_src]["is_won"].mean()
        if top_src != "—" else 0.0
    )

    grp_counts  = filtered["source_group"].value_counts()
    top_group   = grp_counts.idxmax() if not grp_counts.empty else "—"

    c1, c2, c3, c4 = st.columns(4)
    c1.metric(
        "Total Leads (filtered)",
        f"{total_filt:,}",
        delta=f"{total_filt - total_all:+,} vs all" if total_filt != total_all else None,
    )
    c2.metric(
        "Conversion Rate",
        f"{rate_filt * 100:.2f}%",
        delta=f"{(rate_filt - rate_all) * 100:+.2f} pp vs all"
              if total_filt != total_all else None,
        delta_color="normal",
    )
    c3.metric(
        "Top Source",
        top_src,
        delta=f"{top_src_rate * 100:.1f}% win rate  ·  {top_src_n:,} leads",
        delta_color="off",
    )
    c4.metric(
        "Top Source Group",
        top_group,
        delta=f"{int(grp_counts.max()):,} leads" if not grp_counts.empty else None,
        delta_color="off",
    )


# ---------------------------------------------------------------------------
# Overview view
# ---------------------------------------------------------------------------
def render_overview(filtered: pd.DataFrame):
    st.markdown("## 📋 Overview")

    # --- Deal-stage funnel ---
    stage_counts = (
        filtered["deal_stage"]
        .value_counts()
        .reindex([s for s in STAGE_ORDER if s in filtered["deal_stage"].unique()])
        .fillna(0)
        .astype(int)
        .reset_index()
    )
    stage_counts.columns = ["Deal Stage", "Count"]

    col_left, col_right = st.columns(2)

    with col_left:
        st.markdown("### Deal Stage Distribution")
        fig_funnel = go.Figure(go.Bar(
            x=stage_counts["Count"],
            y=stage_counts["Deal Stage"],
            orientation="h",
            marker_color=CLR_BLUE,
            text=stage_counts["Count"].apply(lambda v: f"{v:,}"),
            textposition="outside",
        ))
        fig_funnel.update_layout(
            margin=dict(l=0, r=40, t=10, b=10),
            height=380,
            plot_bgcolor=CLR_BG,
            paper_bgcolor="white",
            xaxis_title="Lead Count",
            yaxis=dict(autorange="reversed"),
        )
        st.plotly_chart(fig_funnel, use_container_width=True)

    # --- Source win-rate bar ---
    with col_right:
        st.markdown("### Win Rate by Lead Source")
        src_summary = (
            filtered.groupby("source", as_index=False)
            .agg(Leads=("source", "size"), Won=("is_won", "sum"))
        )
        src_summary["Win Rate %"] = (src_summary["Won"] / src_summary["Leads"] * 100).round(2)
        src_summary = src_summary.sort_values("Win Rate %", ascending=True)

        fig_rate = go.Figure(go.Bar(
            x=src_summary["Win Rate %"],
            y=src_summary["source"],
            orientation="h",
            marker=dict(
                color=src_summary["Win Rate %"],
                colorscale=[[0, "#fee2e2"], [0.5, CLR_BLUE], [1, CLR_GREEN]],
                showscale=False,
            ),
            text=src_summary["Win Rate %"].apply(lambda v: f"{v:.1f}%"),
            textposition="outside",
        ))
        fig_rate.update_layout(
            margin=dict(l=0, r=50, t=10, b=10),
            height=380,
            plot_bgcolor=CLR_BG,
            paper_bgcolor="white",
            xaxis_title="Win Rate (%)",
            yaxis=dict(autorange="reversed"),
        )
        st.plotly_chart(fig_rate, use_container_width=True)

    # --- Source volume vs conversion scatter ---
    st.markdown("### Lead Volume vs Conversion Rate by Source")
    src_bubble = (
        filtered.groupby("source", as_index=False)
        .agg(Leads=("source", "size"), Won=("is_won", "sum"))
    )
    src_bubble["Win Rate %"] = (src_bubble["Won"] / src_bubble["Leads"] * 100).round(2)

    fig_scatter = px.scatter(
        src_bubble,
        x="Leads", y="Win Rate %",
        text="source",
        size="Leads",
        color="Win Rate %",
        color_continuous_scale=[[0, "#fee2e2"], [0.5, CLR_BLUE], [1, CLR_GREEN]],
        labels={"Leads": "Lead Volume", "Win Rate %": "Win Rate (%)"},
    )
    fig_scatter.update_traces(textposition="top center", textfont_size=10)
    fig_scatter.update_layout(
        height=420,
        plot_bgcolor=CLR_BG,
        paper_bgcolor="white",
        margin=dict(l=0, r=0, t=10, b=10),
        coloraxis_showscale=False,
    )
    st.plotly_chart(fig_scatter, use_container_width=True)

    # --- Sentiment distribution by outcome ---
    st.markdown("### Notes Sentiment Distribution by Outcome")
    sent_df = filtered[["notes_sentiment", "is_won"]].copy()
    sent_df["Outcome"] = sent_df["is_won"].map({1: "Won", 0: "Not Won"})

    fig_sent = px.histogram(
        sent_df, x="notes_sentiment", color="Outcome",
        nbins=40, barmode="overlay", opacity=0.65,
        color_discrete_map={"Won": CLR_GREEN, "Not Won": CLR_RED},
        labels={"notes_sentiment": "Notes Sentiment (TextBlob polarity)"},
    )
    fig_sent.update_layout(
        height=280, plot_bgcolor=CLR_BG, paper_bgcolor="white",
        margin=dict(l=0, r=0, t=10, b=10),
    )
    st.plotly_chart(fig_sent, use_container_width=True)


# ---------------------------------------------------------------------------
# Performance view
# ---------------------------------------------------------------------------
def render_performance(filtered: pd.DataFrame):
    st.markdown("## 📈 Source & Channel Performance")

    # Source group summary
    grp = (
        filtered.groupby("source_group", as_index=False)
        .agg(Leads=("source_group", "size"), Won=("is_won", "sum"))
    )
    grp["Win Rate %"] = (grp["Won"] / grp["Leads"] * 100).round(2)
    grp = grp.sort_values("Win Rate %", ascending=False)

    col1, col2 = st.columns(2)
    with col1:
        st.markdown("### Source Group Win Rate")
        fig_grp = go.Figure(go.Bar(
            x=grp["source_group"], y=grp["Win Rate %"],
            marker_color=CLR_PURPLE,
            text=grp["Win Rate %"].apply(lambda v: f"{v:.2f}%"),
            textposition="outside",
        ))
        fig_grp.update_layout(
            height=320, plot_bgcolor=CLR_BG, paper_bgcolor="white",
            margin=dict(l=0, r=0, t=10, b=10),
            yaxis_title="Win Rate (%)", xaxis_title="Source Group",
        )
        st.plotly_chart(fig_grp, use_container_width=True)

    with col2:
        st.markdown("### Source Group Volume")
        fig_vol = go.Figure(go.Bar(
            x=grp["source_group"], y=grp["Leads"],
            marker_color=CLR_BLUE,
            text=grp["Leads"].apply(lambda v: f"{v:,}"),
            textposition="outside",
        ))
        fig_vol.update_layout(
            height=320, plot_bgcolor=CLR_BG, paper_bgcolor="white",
            margin=dict(l=0, r=0, t=10, b=10),
            yaxis_title="Leads", xaxis_title="Source Group",
        )
        st.plotly_chart(fig_vol, use_container_width=True)

    # Full source×group heatmap (all sources in filtered data)
    st.markdown("### Source × Source Group Win Rate Heatmap")
    pivot = (
        filtered.pivot_table(
            index="source_group", columns="source",
            values="is_won", aggfunc="mean"
        ) * 100
    ).round(2)

    fig_heat = px.imshow(
        pivot,
        text_auto=".1f",
        color_continuous_scale=[[0, "#fef9c3"], [0.5, CLR_BLUE], [1, CLR_GREEN]],
        labels=dict(x="Source", y="Source Group", color="Win Rate (%)"),
        aspect="auto",
    )
    fig_heat.update_layout(
        height=260,
        margin=dict(l=0, r=0, t=10, b=10),
        paper_bgcolor="white",
    )
    st.plotly_chart(fig_heat, use_container_width=True)

    # Won vs Not-Won stacked bar by source
    st.markdown("### Won / Not-Won Stacked Bar by Source")
    src_stack = (
        filtered.groupby(["source", "is_won"], as_index=False)
        .size()
        .rename(columns={"size": "Count"})
    )
    src_stack["Outcome"] = src_stack["is_won"].map({1: "Won", 0: "Not Won"})
    src_order = (
        filtered.groupby("source")["is_won"].mean()
        .sort_values(ascending=False).index.tolist()
    )
    fig_stack = px.bar(
        src_stack,
        x="source", y="Count", color="Outcome",
        color_discrete_map={"Won": CLR_GREEN, "Not Won": CLR_RED},
        category_orders={"source": src_order},
        barmode="stack",
        labels={"source": "Lead Source", "Count": "Lead Count"},
    )
    fig_stack.update_layout(
        height=340, plot_bgcolor=CLR_BG, paper_bgcolor="white",
        margin=dict(l=0, r=0, t=10, b=10),
        xaxis_tickangle=-35,
    )
    st.plotly_chart(fig_stack, use_container_width=True)

    # Summary table
    st.markdown("### Full Source Summary Table")
    src_tbl = (
        filtered.groupby("source", as_index=False)
        .agg(
            Leads=("source", "size"),
            Won=("is_won", "sum"),
        )
    )
    src_tbl["Win Rate %"] = (src_tbl["Won"] / src_tbl["Leads"] * 100).round(2)
    src_tbl["Lost"]       = src_tbl["Leads"] - src_tbl["Won"]
    src_tbl["Tier"]       = src_tbl["source"].map(SOURCE_TIER)
    src_tbl = src_tbl.sort_values("Win Rate %", ascending=False).reset_index(drop=True)
    st.dataframe(
        src_tbl[["source", "Tier", "Leads", "Won", "Lost", "Win Rate %"]],
        use_container_width=True, hide_index=True,
    )


# ---------------------------------------------------------------------------
# Explainability view  (loads Phase 6 JSON – no re-computation)
# ---------------------------------------------------------------------------
def render_explainability():
    st.markdown("## 🔬 Model Explainability (Phase 6 Results)")

    expl = load_explainability()
    if not expl:
        st.warning(f"Explainability JSON not found at `{EXPL_PATH}`.")
        return

    metrics = load_metrics()

    # Model performance summary
    if metrics:
        bm = metrics.get("best_model", {})
        model_name = bm.get("name", "Logistic Regression")
        val_auc    = bm.get("val_roc_auc", "—")
        st.info(
            f"**Best model:** {model_name}  ·  "
            f"**Validation ROC-AUC:** {val_auc}  ·  "
            f"Selection criterion: {bm.get('selection_criterion', '—')}"
        )

    tab1, tab2, tab3, tab4 = st.tabs(
        ["SHAP Global (G5)", "Permutation (G4)", "LR Coefficients (G1)", "Local Cases (L1)"]
    )

    # --- G5 SHAP ---
    with tab1:
        st.markdown("### SHAP Mean |Value| — Global Feature Importance (RF)")
        shap_data = pd.DataFrame(expl.get("g5_shap_mean_abs", []))
        if not shap_data.empty:
            shap_data = shap_data.sort_values("mean_abs_shap", ascending=True).tail(20)
            fig = go.Figure(go.Bar(
                x=shap_data["mean_abs_shap"],
                y=shap_data["feature"],
                orientation="h",
                marker_color=CLR_GREEN,
                text=shap_data["mean_abs_shap"].apply(lambda v: f"{v:.5f}"),
                textposition="outside",
            ))
            fig.update_layout(
                height=520, plot_bgcolor=CLR_BG, paper_bgcolor="white",
                margin=dict(l=0, r=80, t=10, b=10),
                xaxis_title="Mean |SHAP value|",
            )
            st.plotly_chart(fig, use_container_width=True)
        st.caption(
            "⚠️ **Association, not causation.** SHAP values describe what the model "
            "learned from training data — not causal relationships between features and conversion."
        )

    # --- G4 Permutation ---
    with tab2:
        st.markdown("### Permutation Importance — ROC-AUC Drop (15 repeats, RF test set)")
        perm_data = pd.DataFrame(expl.get("g4_permutation_importance", []))
        if not perm_data.empty:
            perm_data = perm_data.sort_values("mean_drop", ascending=True)
            colors    = [CLR_GREEN if v > 0.001 else CLR_RED if v < -0.001
                         else CLR_MUTED for v in perm_data["mean_drop"]]
            fig = go.Figure(go.Bar(
                x=perm_data["mean_drop"],
                y=perm_data["feature"],
                orientation="h",
                marker_color=colors,
                error_x=dict(type="data", array=perm_data["std_drop"].tolist(),
                             color="#374151", thickness=1.2),
                text=perm_data["mean_drop"].apply(lambda v: f"{v:+.5f}"),
                textposition="outside",
            ))
            fig.add_vline(x=0, line_dash="dash", line_color="#374151")
            fig.update_layout(
                height=360, plot_bgcolor=CLR_BG, paper_bgcolor="white",
                margin=dict(l=0, r=90, t=10, b=10),
                xaxis_title="Mean ROC-AUC drop (positive = model degrades when shuffled)",
            )
            st.plotly_chart(fig, use_container_width=True)
        st.caption(
            "⚠️ All values are within ±0.01 of zero — no feature provides genuine "
            "predictive lift beyond random chance (ROC-AUC ≈ 0.50–0.51). "
            "See Phase 7 recommendations for required additional features."
        )

    # --- G1 LR Coefficients ---
    with tab3:
        st.markdown("### Logistic Regression Signed Coefficients (Best Model)")
        lr_data = pd.DataFrame(expl.get("g1_lr_coefficients", []))
        if not lr_data.empty:
            lr_data = lr_data.sort_values("coefficient", ascending=True)
            colors  = [CLR_RED if v < 0 else CLR_GREEN for v in lr_data["coefficient"]]
            fig = go.Figure(go.Bar(
                x=lr_data["coefficient"],
                y=lr_data["feature"],
                orientation="h",
                marker_color=colors,
                text=lr_data["coefficient"].apply(lambda v: f"{v:+.4f}"),
                textposition="outside",
            ))
            fig.add_vline(x=0, line_color="#374151")
            fig.update_layout(
                height=680, plot_bgcolor=CLR_BG, paper_bgcolor="white",
                margin=dict(l=0, r=80, t=10, b=10),
                xaxis_title="Coefficient (positive → model predicts Won)",
            )
            st.plotly_chart(fig, use_container_width=True)
        st.caption(
            "⚠️ Max |coefficient| < 0.04 — all coefficients are near-zero, "
            "confirming the model has essentially not learned a meaningful signal."
        )

    # --- L1 Local Cases ---
    with tab4:
        st.markdown("### SHAP Waterfall — Representative Individual Predictions")
        cases = expl.get("l1_local_cases", {})
        case_meta = {
            "tp": ("✅ True Positive",  "High prob · Actual = Won",      CLR_GREEN),
            "fp": ("❌ False Positive", "High prob · Actual = Not Won",   CLR_RED),
            "fn": ("⚠️ False Negative", "Low prob  · Actual = Won",      CLR_AMBER),
            "tn": ("✓  True Negative",  "Low prob  · Actual = Not Won",  CLR_BLUE),
        }
        for key, (label, subtitle, color) in case_meta.items():
            c = cases.get(key, {})
            if not c:
                continue
            with st.expander(f"{label}  —  {subtitle}  |  Pred={c['predicted_prob']:.4f}  |  Actual={c['actual_label']}"):
                feats = pd.DataFrame(c.get("top_shap_features", []))
                if feats.empty:
                    continue
                feats = feats.sort_values("shap_value", ascending=True)
                bar_colors = [CLR_GREEN if v > 0 else CLR_RED for v in feats["shap_value"]]
                fig = go.Figure(go.Bar(
                    x=feats["shap_value"],
                    y=feats["feature"],
                    orientation="h",
                    marker_color=bar_colors,
                    text=feats["shap_value"].apply(lambda v: f"{v:+.4f}"),
                    textposition="outside",
                ))
                fig.add_vline(x=0, line_color="#374151")
                fig.update_layout(
                    height=320, plot_bgcolor=CLR_BG, paper_bgcolor="white",
                    margin=dict(l=0, r=80, t=10, b=10),
                    xaxis_title="SHAP value (contribution to predicted probability)",
                    title=dict(text=f"{label}  ·  Predicted prob = {c['predicted_prob']:.4f}",
                               font_size=12),
                )
                st.plotly_chart(fig, use_container_width=True)

        cbs = expl.get("causal_boundary_statement", {})
        if cbs:
            st.markdown("---")
            st.markdown("### ⚠️ Causal Boundary Statement")
            for key, title in [
                ("global_importance",    "Global Importance ≠ Causation"),
                ("local_predictions",    "Local Predictions ≠ Causal Mechanisms"),
                ("permutation_finding",  "Permutation Test Confirms No Genuine Signal"),
                ("practical_implication","Practical Implication"),
            ]:
                if key in cbs:
                    st.warning(f"**{title}:** {cbs[key]}")


# ---------------------------------------------------------------------------
# What-If Scorer view
# ---------------------------------------------------------------------------
def render_scorer(full_df: pd.DataFrame):
    st.markdown("## 🎯 What-If Lead Scorer")
    st.caption(
        "Adjust lead attributes to score them live with the trained Phase 5 pipeline.  \n"
        "The model outputs a probability calibrated against the training distribution."
    )

    total, owner_counts, company_counts = compute_freq_tables(full_df)

    sources       = sorted(full_df["source"].dropna().unique())
    source_groups = sorted(full_df["source_group"].dropna().unique())

    col_form, col_result = st.columns([2, 1])

    with col_form:
        with st.form("what_if_scorer", border=True):
            st.markdown("#### Lead Attributes")
            r1c1, r1c2 = st.columns(2)
            score_source = r1c1.selectbox("Lead Source", sources, index=0)
            score_group  = r1c2.selectbox(
                "Source Group", source_groups,
                index=source_groups.index("Inbound") if "Inbound" in source_groups else 0,
            )

            r2c1, r2c2 = st.columns(2)
            # Owner: free text (frequency-encoded at score time)
            score_owner   = r2c1.text_input("Lead Owner", value="Alice Johnson")
            company_name  = r2c2.text_input("Company", value="Acme Corp")

            st.markdown("#### Notes Features")
            r3c1, r3c2, r3c3 = st.columns(3)
            notes_sentiment  = r3c1.slider(
                "Sentiment", min_value=-1.0, max_value=1.0, value=0.20, step=0.05,
                help="TextBlob polarity. 0 = neutral.",
            )
            notes_word_count = r3c2.number_input(
                "Word Count", min_value=0, max_value=5000, value=120,
                help="Number of words in the lead notes.",
            )
            notes_has_text = r3c3.checkbox("Has Text", value=True)

            submitted = st.form_submit_button("▶  Score Lead", use_container_width=True)

    with col_result:
        st.markdown("#### Prediction")
        if not submitted:
            st.info("Fill in the form and click **Score Lead**.")
        else:
            try:
                model = load_model()
            except (FileNotFoundError, OSError) as err:
                st.error(f"Cannot load model: {err}")
                return

            vec = build_vector(
                source=score_source,
                source_group=score_group,
                notes_sentiment=notes_sentiment,
                notes_word_count=int(notes_word_count),
                notes_has_text=1 if notes_has_text else 0,
                lead_owner=score_owner,
                company=company_name,
                owner_counts=owner_counts,
                company_counts=company_counts,
                total=total,
            )

            try:
                prob   = float(model.predict_proba([vec])[0, 1])
                label  = "Likely Won" if prob >= 0.5 else "Likely Lost"
                colour = CLR_GREEN if prob >= 0.5 else CLR_RED
            except Exception as err:
                st.error(f"Scoring error: {err}")
                return

            # Gauge chart
            fig_gauge = go.Figure(go.Indicator(
                mode="gauge+number+delta",
                value=prob * 100,
                delta={"reference": 9.99, "suffix": " pp vs base rate"},
                number={"suffix": "%", "font": {"size": 36}},
                gauge={
                    "axis": {"range": [0, 100], "tickwidth": 1},
                    "bar":  {"color": colour},
                    "steps": [
                        {"range": [0, 30],  "color": "#fee2e2"},
                        {"range": [30, 50], "color": "#fef3c7"},
                        {"range": [50, 100],"color": "#dcfce7"},
                    ],
                    "threshold": {
                        "line": {"color": "#374151", "width": 2},
                        "thickness": 0.8, "value": 50,
                    },
                },
                title={"text": label, "font": {"size": 18, "color": colour}},
            ))
            fig_gauge.update_layout(
                height=260, margin=dict(l=10, r=10, t=30, b=10),
                paper_bgcolor="white",
            )
            st.plotly_chart(fig_gauge, use_container_width=True)

            st.metric("Win Probability", f"{prob * 100:.2f}%")
            st.metric("Prediction Class", label)

            tier = SOURCE_TIER.get(score_source, 2)
            tier_label = {1: "Tier 1 (High)", 2: "Tier 2 (Mid)", 3: "Tier 3 (Low)"}[tier]
            st.caption(f"Source tier: **{tier_label}**")

    # Feature contribution breakdown
    if submitted:
        st.markdown("---")
        st.markdown("#### Feature Contribution Breakdown")
        st.caption(
            "Approximate contribution of each feature group to the predicted score, "
            "based on the Phase 6 SHAP ranking (ordering only — not per-sample SHAP)."
        )

        expl     = load_explainability()
        shap_map = {
            row["feature"]: row["mean_abs_shap"]
            for row in expl.get("g5_shap_mean_abs", [])
        }

        # Build approximate feature-contribution display
        feature_display = [
            ("Lead Source",    score_source,              shap_map.get("source_tier", 0.002668)),
            ("Source Group",   score_group,               shap_map.get("source_group_Inbound", 0.001789)),
            ("Notes Sentiment",f"{notes_sentiment:+.2f}", shap_map.get("notes_sentiment", 0.005179)),
            ("Notes Word Count",str(notes_word_count),    shap_map.get("notes_word_count", 0.005713)),
            ("Company Freq",   company_name,              shap_map.get("company_freq", 0.004284)),
            ("Owner Freq",     score_owner,               shap_map.get("owner_freq", 0.001753)),
        ]
        contrib_df = pd.DataFrame(
            feature_display, columns=["Feature Group", "Value", "Global Importance (mean|SHAP|)"]
        ).sort_values("Global Importance (mean|SHAP|)", ascending=True)

        fig_contrib = go.Figure(go.Bar(
            x=contrib_df["Global Importance (mean|SHAP|)"],
            y=contrib_df["Feature Group"],
            orientation="h",
            marker_color=CLR_BLUE,
            text=contrib_df["Value"],
            textposition="outside",
        ))
        fig_contrib.update_layout(
            height=280, plot_bgcolor=CLR_BG, paper_bgcolor="white",
            margin=dict(l=0, r=160, t=10, b=10),
            xaxis_title="Global SHAP importance (mean |SHAP|)",
        )
        st.plotly_chart(fig_contrib, use_container_width=True)
        st.caption(
            "⚠️ These are **global** importances from Phase 6 — not per-sample SHAP values. "
            "The model ROC-AUC is ~0.51 (near-random); scores should be interpreted as "
            "directional associations, not precise predictions."
        )


# ---------------------------------------------------------------------------
# AI Insights view  (Phase 8 — loads pre-generated ai_narrative.json)
# ---------------------------------------------------------------------------
_RATING_ICON  = {"positive": "✅", "neutral": "ℹ️", "warning": "⚠️"}
_RATING_COLOR = {"positive": "#dcfce7", "neutral": "#f0f9ff", "warning": "#fef3c7"}
_RATING_BORDER= {"positive": "#22c55e", "neutral": "#3b82d4",  "warning": "#f59e0b"}
_CAT_BADGE    = {
    "Data":            "#dbeafe",
    "KPI":             "#ede9fe",
    "Analytics":       "#dcfce7",
    "Feature Analysis":"#fef3c7",
    "ML":              "#fee2e2",
    "Explainability":  "#fce7f3",
    "Recommendations": "#d1fae5",
    "Methodology":     "#f1f5f9",
}


def render_ai_insights() -> None:
    st.markdown("## 🤖 AI Insights — Executive Summary (Phase 8)")

    narrative = load_narrative()

    if not narrative:
        st.warning(
            f"AI narrative file not found at `{NARRATIVE_PATH}`.  \n"
            "Run `python src/ai_narrative.py` to generate it."
        )
        return

    # ── Provenance banner
    source      = narrative.get("narrative_source", "heuristic_fallback")
    wx_enabled  = narrative.get("watsonx_enabled", False)
    wx_model    = narrative.get("watsonx_model", "ibm/granite-13b-chat-v2")

    if source == "watsonx":
        st.success(
            f"🟢 **Narrative generated by IBM watsonx.ai** · Model: `{wx_model}`  \n"
            "Every statistic in this summary was sourced from validated Phase 3–6 outputs."
        )
    else:
        st.info(
            "🔵 **Narrative generated by rule-based heuristic fallback**  \n"
            "watsonx.ai credentials not configured (`WATSONX_APIKEY` / `PROJECT_ID`).  \n"
            "All numbers are sourced directly from validated Phase 3–6 JSON outputs — "
            "no values are invented."
        )

    # ── Context snapshot
    snap = narrative.get("context_snapshot", {})
    if snap:
        with st.expander("📊 Context snapshot (values used to generate this narrative)"):
            snap_df = pd.DataFrame([
                {"Metric": k, "Value": v} for k, v in snap.items()
            ])
            st.dataframe(snap_df, use_container_width=True, hide_index=True)

    st.markdown("---")

    # ── Narrative text (full executive summary)
    st.markdown("### Executive Briefing")
    narrative_text = narrative.get("narrative", "")
    if narrative_text:
        # Render each section as a distinct block
        sections = narrative_text.strip().split("\n\n")
        for section in sections:
            if section.strip():
                lines = section.strip().split("\n")
                header = lines[0].strip()
                body   = "\n".join(lines[1:]).strip()
                if header in ("EXECUTIVE SUMMARY", "KEY FINDINGS", "RECOMMENDATIONS"):
                    st.markdown(f"**{header}**")
                    if body:
                        st.markdown(body)
                else:
                    st.markdown(section.strip())
                st.markdown("")

    st.markdown("---")

    # ── Structured insight cards
    insights = narrative.get("insights", [])
    if not insights:
        st.info("No structured insights found in the narrative file.")
        return

    st.markdown("### Structured Insights")
    st.caption(
        f"{len(insights)} insight blocks · all values sourced from validated pipeline outputs · "
        f"source: `{source}`"
    )

    # Group by category for display
    categories = list(dict.fromkeys(ins["category"] for ins in insights))
    tabs_list  = st.tabs(categories)

    cat_map: dict[str, list] = {cat: [] for cat in categories}
    for ins in insights:
        cat_map[ins["category"]].append(ins)

    for tab, cat in zip(tabs_list, categories):
        with tab:
            for ins in cat_map[cat]:
                rating  = ins.get("rating", "neutral")
                icon    = _RATING_ICON.get(rating, "ℹ️")
                bg      = _RATING_COLOR.get(rating, "#f7f8fa")
                border  = _RATING_BORDER.get(rating, "#e5e7eb")
                badge_c = _CAT_BADGE.get(cat, "#f7f8fa")
                st.markdown(
                    f"""<div style="
                        background:{bg};
                        border-left:4px solid {border};
                        border-radius:4px;
                        padding:10px 14px;
                        margin-bottom:12px;
                    ">
                    <span style="
                        background:{badge_c};
                        border-radius:3px;
                        padding:1px 6px;
                        font-size:11px;
                        font-weight:600;
                        margin-right:6px;
                    ">{cat}</span>
                    <strong>{icon} {ins['title']}</strong><br/>
                    <span style="font-size:13px;line-height:1.6;">{ins['text']}</span>
                    </div>""",
                    unsafe_allow_html=True,
                )

    # ── Causal boundary reminder
    st.markdown("---")
    st.warning(
        "⚠️ **Causal boundary:** All insights above describe statistical associations "
        "observed in the dataset. They do not establish causal relationships. "
        "Higher win rates for specific channels may reflect unmeasured confounders "
        "(lead quality, industry segment, deal size, sales rep assignment). "
        "Validate recommendations through controlled A/B experiments."
    )

    # ── Re-generate button (runs the narrative script in-process)
    st.markdown("---")
    st.markdown("#### Regenerate Narrative")
    st.caption(
        "Re-runs `src/ai_narrative.py` in-process using current pipeline outputs. "
        "Set `WATSONX_APIKEY` + `PROJECT_ID` environment variables before clicking "
        "to use IBM watsonx.ai Granite instead of the heuristic fallback."
    )
    if st.button("🔄 Regenerate AI Narrative", help="Clears cache and rebuilds the narrative"):
        # Import inline to avoid circular load at module level
        import sys
        sys.path.insert(0, str(ROOT))
        try:
            import importlib
            import src.ai_narrative as _narr
            importlib.reload(_narr)
            ctx    = _narr.build_context()
            result = _narr.generate_summary(ctx)
            payload = {
                "generated_by":    "src/ai_narrative.py (dashboard regenerate)",
                "narrative_source": result["source"],
                "watsonx_enabled":  result["watsonx_enabled"],
                "watsonx_model":    os.environ.get("WATSONX_MODEL_ID",
                                                    "ibm/granite-13b-chat-v2"),
                "context_snapshot": {
                    k: ctx[k] for k in [
                        "total_leads", "win_rate_pct", "top_source",
                        "top_source_rate", "win_rate_spread",
                        "best_model_name", "best_val_auc",
                        "perm_max", "perm_min", "top_shap_feature",
                    ]
                },
                "narrative":  result["narrative_text"],
                "insights":   result["insights"],
            }
            with open(NARRATIVE_PATH, "w", encoding="utf-8") as fh:
                json.dump(payload, fh, indent=2, ensure_ascii=False)
            load_narrative.clear()
            st.success(
                f"Narrative regenerated ({result['source']}) and saved to "
                f"`{NARRATIVE_PATH.name}`. Reload the page to see the updated content."
            )
        except Exception as err:
            st.error(f"Regeneration failed: {err}")


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------
def main():
    # Load data (cached)
    try:
        df = load_data()
    except (FileNotFoundError, ValueError) as err:
        st.error(f"**Data load failed:** {err}")
        st.stop()

    view, filtered = render_sidebar(df)

    st.title("📊 Lead Intelligence Dashboard")
    st.caption(
        "All metrics computed dynamically from `data/processed/cleaned_leads.csv` "
        "and `models/best_model.pkl` (Phase 5 pipeline)."
    )

    if filtered.empty:
        st.warning("⚠️ No records match the current filters. Adjust the sidebar selections.")
        return

    # KPI cards always visible
    render_kpis(df, filtered)
    st.markdown("---")

    # Route to selected view
    view_key = view.split(" ", 1)[1]  # strip emoji prefix
    if view_key == "Overview":
        render_overview(filtered)
    elif view_key == "Performance":
        render_performance(filtered)
    elif view_key == "Explainability":
        render_explainability()
    elif view_key == "AI Insights":
        render_ai_insights()
    else:
        render_scorer(df)


if __name__ == "__main__":
    main()
